### PR TITLE
Manifest

### PR DESCRIPTION
**Pull request by alexpsi**

### CODE REVIEW

**Comment by matthewjackowski** [comment]
Fyi, guys
There are 2 levels of testing here.  What runs on Travis is just a quick sanity check to ensure that the plugin works in a clean build of Wordpress.
Additionally the full 'acceptance' tests are located here: https://github.com/transifex/transifex-live-wordpress/tree/accept
I had to separate them because the acceptance tests won't run on Travis.

**Comment by SofiaMargariti** [comment]
Thanks @matthewjackowski! Will check them out both. Is there any guide on how the acceptance are getting triggered or how to run them manually?

**Comment by matthewjackowski** [comment]
Unfortunately it doesn't appear that I wrote anything specific to this project.  So you should be able to run them by just following the Codeception framework quickstart (skipping the bits where you write the tests of course).  http://codeception.com/quickstart

**Comment by matthewjackowski** [comment]
Also, please note, if you disable the scripts in Travis, be sure you manually check a clean Wordpress build manually. This is the setup where Wordpress is completely new and the plugin is installed for the first time.  Typically this isn't covered through normal testing as once the settings are initialized they are persisted.  So there can be errors in that initialization that you wouldn't otherwise catch.

This is why I wrote the Travis tests, because I got sick of re-installing WP all the time. ;)

**Pull request merged**
